#
# Automatically generated by mdiswiz 2.04.00-linux-12.4
# 2017-01-12
#

cpu {

    # ------------------------------------------------------------------------
    #        general parameters (don't modify)
    # ------------------------------------------------------------------------
    DESC_TYPE = U_INT32 0x0
    HW_TYPE = STRING A20
    _WIZ_MODEL = STRING A20
}
a201_1 {

    # ------------------------------------------------------------------------
    #        general parameters (don't modify)
    # ------------------------------------------------------------------------
    DESC_TYPE = U_INT32 0x2
    HW_TYPE = STRING A201_SW
    _WIZ_MODEL = STRING A201
    _WIZ_BUSIF = STRING cpu,0
    VME_A24_ADDR = U_INT32 0xe00000
    VME_DATA_WIDTH = U_INT32 0x1
    IRQ_VECTOR = BINARY 0x80,0x81,0x82,0x83
    IRQ_LEVEL = BINARY 0x3,0x3,0x3,0x3

    # ------------------------------------------------------------------------
    #        debug levels (optional)
    #        these keys have only effect on debug drivers
    # ------------------------------------------------------------------------
    DEBUG_LEVEL = U_INT32 0xc0008007
    DEBUG_LEVEL_BK = U_INT32 0xc0008007
    DEBUG_LEVEL_OSS = U_INT32 0xc0008007
    DEBUG_LEVEL_DESC = U_INT32 0xc0008007
}
m99_1 {

    # ------------------------------------------------------------------------
    #        general parameters (don't modify)
    # ------------------------------------------------------------------------
    DESC_TYPE = U_INT32 0x1
    HW_TYPE = STRING M99_SW
# HW_TYPE = STRING M99
    _WIZ_MODEL = STRING M99

    # ------------------------------------------------------------------------
    #        reference to base board
    # ------------------------------------------------------------------------
    BOARD_NAME = STRING a201_1
    DEVICE_SLOT = U_INT32 0x0

    # ------------------------------------------------------------------------
    #        device parameters
    # ------------------------------------------------------------------------

    # Define wether M-Module ID-PROM is checked, don't enable for M99, works only once after power up
    # 0 := disable -- ignore IDPROM
    # 1 := enable
    ID_CHECK = U_INT32 0

    # ------------------------------------------------------------------------
    #        debug levels (optional)
    #        these keys have only effect on debug drivers
    # ------------------------------------------------------------------------
    DEBUG_LEVEL = U_INT32 0xc0008000
    DEBUG_LEVEL_MK = U_INT32 0xc0008000
    DEBUG_LEVEL_OSS = U_INT32 0xc0008000
    DEBUG_LEVEL_DESC = U_INT32 0xc0008000
    DEBUG_LEVEL_MBUF = U_INT32 0xc0008000
}
# EOF
